# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentgate < Formula
  desc "AgentGate — Zero-Trust Semantic Firewall and Protocol Bridge for MCP"
  homepage "https://github.com/AgentStaqAI/agentgate"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AgentStaqAI/agentgate/releases/download/v0.2.0/agentgate_Darwin_x86_64.tar.gz"
      sha256 "1f3690fc099cb662183b325bc10a95dd8d9fdcaf6012942597d063571b879c31"

      define_method(:install) do
        bin.install "agentgate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AgentStaqAI/agentgate/releases/download/v0.2.0/agentgate_Darwin_arm64.tar.gz"
      sha256 "ce439d5c3bc3ee2a738becfaca651dfece28430969bb7602841b8f173f5c8639"

      define_method(:install) do
        bin.install "agentgate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentStaqAI/agentgate/releases/download/v0.2.0/agentgate_Linux_x86_64.tar.gz"
      sha256 "e05aabef564d623cbc424f61ab99f90692dec72dd1a23191cee4a186b9ab61b4"
      define_method(:install) do
        bin.install "agentgate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AgentStaqAI/agentgate/releases/download/v0.2.0/agentgate_Linux_arm64.tar.gz"
      sha256 "00d6678dd2d1018f8265cb58f1d3642480e8b403b6c4036875c9276c186b2eef"
      define_method(:install) do
        bin.install "agentgate"
      end
    end
  end
end
